function make_comparison_plot(MKL_6, DFS_6, BFS_6, HYBRID_6, ...
    MKL_24, DFS_24, BFS_24, HYBRID_24, dims, title_str, out_name, use_legend)


lw = 1.75;      % LineWidth
msz = 14;       % MarkerSize
width = 8; height = 6;
make_plot_pre(width, height);
plot(dims, MKL_6,  'black*-', ...
     dims, MKL_24,  'blacko-', ...
     dims, DFS_6, 'g+--', ...
     dims, BFS_6, 'bp--', ...
     dims, HYBRID_6, 'cs--', ...
     dims, DFS_24, 'yx--', ...    
     dims, BFS_24, 'r^--', ...
     dims, HYBRID_24, 'md--', ...
     'LineWidth', lw, 'MarkerSize', msz);
 if use_legend
  legend('MKL, 6 cores', 'MKL, 24 cores', 'DFS, 6 cores', 'BFS, 6 cores', 'HYBRID, 6 cores', ...
      'DFS, 24 cores', 'BFS, 24 cores', 'HYBRID, 24 cores', 'Location', 'SouthEast');
 end
  xlabel('Dimension (N)');
  ylabel('Effective GFLOPS / core');
  ylim([0, 27]);
  
  curtick = [0, 5000, 10000, 15000, 20000]; set(gca, 'XTickLabel', cellstr(num2str(curtick(:))));
  
  title(title_str); %, 'interpreter', 'latex');
  
 make_plot_post(width, height);
 
 print(sprintf('fast-matmul_paper_figs/%s', out_name), '-depsc','-r300');